from datetime import datetime, timezone


class AlertManager:
    """Manage alerts generated by transaction analysis."""

    def __init__(self):
        self.alerts = []

    def create_alert(
        self,
        transaction_id: str,
        analysis: dict,
    ) -> dict | None:
        """Create an alert when a transaction requires investigation."""

        risk_score = analysis["risk_score"]
        risk_level = analysis["risk_level"]

        # Only HIGH and CRITICAL transactions become alerts.
        if risk_score < 60:
            return None

        alert = {
            "id": f"alert-{transaction_id}",
            "transaction_id": transaction_id,
            "risk_score": risk_score,
            "risk_level": risk_level,
            "reasons": analysis["evidence"],
            "recommended_action": analysis["recommended_action"],
            "created_at": datetime.now(timezone.utc).isoformat(),
            "status": "OPEN",
        }

        self.alerts.append(alert)

        return alert

    def get_alerts(self) -> list[dict]:
        """Return all generated alerts."""

        return self.alerts

    def get_alert(self, alert_id: str) -> dict | None:
        """Return a specific alert."""

        return next(
            (
                alert
                for alert in self.alerts
                if alert["id"] == alert_id
            ),
            None,
        )

    def active_alert_count(self) -> int:
        """Return the number of open alerts."""

        return sum(
            1
            for alert in self.alerts
            if alert["status"] == "OPEN"
        )